[build]
  command = "yarn build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "yarn dev"
  port = 8888
  targetPort = 5173
