/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Ingredient = {
  _type: 'ingredient';
  name?: string;
  amount?: string;
  unit?: string;
};

export type Recipe = {
  _id: string;
  _type: 'recipe';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  ingredients?: Array<
    {
      _key: string;
    } & Ingredient
  >;
  instructions?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  cookingTime?: number;
  servings?: number;
  category?:
    | 'Sn\xEDdan\u011B'
    | 'Hlavn\xED j\xEDdlo'
    | 'Dezert'
    | 'Drink'
    | 'Sva\u010Dina';
  featured?: boolean;
  publishedAt?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Ingredient
  | Recipe
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/features/recipes/api/queries.ts
// Variable: FEATURED_RECIPES_QUERY
// Query: *[_type == "recipe" && featured == true] | order(publishedAt desc) {  _id,  title,  slug,  description,  mainImage { asset -> { url } },  cookingTime,  servings,  category}
export type FEATURED_RECIPES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  mainImage: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  cookingTime: number | null;
  servings: number | null;
  category:
    | 'Dezert'
    | 'Drink'
    | 'Hlavn\xED j\xEDdlo'
    | 'Sn\xEDdan\u011B'
    | 'Sva\u010Dina'
    | null;
}>;
// Variable: RECIPE_BY_SLUG_QUERY
// Query: *[_type == "recipe" && slug.current == $slug][0] {  _id,  title,  slug,  description,  mainImage { asset -> { url } },  ingredients,  instructions,  cookingTime,  servings,  category,  publishedAt}
export type RECIPE_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  mainImage: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  ingredients: Array<
    {
      _key: string;
    } & Ingredient
  > | null;
  instructions: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  cookingTime: number | null;
  servings: number | null;
  category:
    | 'Dezert'
    | 'Drink'
    | 'Hlavn\xED j\xEDdlo'
    | 'Sn\xEDdan\u011B'
    | 'Sva\u010Dina'
    | null;
  publishedAt: string | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "recipe" && featured == true] | order(publishedAt desc) {\n  _id,\n  title,\n  slug,\n  description,\n  mainImage { asset -> { url } },\n  cookingTime,\n  servings,\n  category\n}': FEATURED_RECIPES_QUERYResult;
    '*[_type == "recipe" && slug.current == $slug][0] {\n  _id,\n  title,\n  slug,\n  description,\n  mainImage { asset -> { url } },\n  ingredients,\n  instructions,\n  cookingTime,\n  servings,\n  category,\n  publishedAt\n}': RECIPE_BY_SLUG_QUERYResult;
  }
}
